-- AlterTable
ALTER TABLE `coin_transactions` MODIFY `source` ENUM('EXAM_CORRECT', 'SHOP_PURCHASE', 'LESSON', 'MODULE', 'COURSE', 'PREMIUM_GRANT', 'LEAGUE_REWARD', 'ADMIN', 'PAYMENT', 'TUTORIAL_REWARD') NOT NULL;
